### ISSUE TITLE
[Bug] AkaneField的声音提示路径问题

### ISSUE THREAD

**Issue by angushushu** [FallenCrystal/CubeX-Log#108]
**描述**
导致部分玩家掉线，显示Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_151" Non [a-z0-9/._-] character in path of location: minecraft:minecraft:entity.wither.spawn

**附加内容**
按照akari提示在config中增加了
```
sounds:
    enabled: false
```
reload后又出现了一次。值得注意的是config中本身是没有sounds这一选项的，所以我不确定我是否正确理解了akari的提示。

**Comment by FallenCrystal** [comment]
`notifications.underattack.sound.enabled`

**Comment by angushushu** [comment]
AkaneField版本是3.0.1，配置文件里没有notification，我自己添加、
```
notifications:
    underattack:
        sound:
            enabled: false
```
这样子？是sound不是sounds是吧
